### ISSUE TITLE
Internal server error when going to homepage

### ISSUE THREAD

**Issue by zoltanszogyenyi** [themesberg/flowbite-svelte#1123]
### Describe the bug

When I go to the homepage from a link from docs the website doesn't work

![IMG_1075](https://github.com/themesberg/flowbite-svelte/assets/8052108/98494778-1e3b-4d5c-936c-2fc3d0f0406d)

### Reproduction

When I go to the homepage from a link from docs the website doesn't work

### Flowbite version and System Info

```shell
System:
    OS: macOS 13.4.1
    CPU: (12) x64 Intel(R) Core(TM) i5-10600 CPU @ 3.30GHz
    Memory: 30.45 GB / 72.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.13.0 - ~/.nvm/versions/node/v18.13.0/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v18.13.0/bin/yarn
    npm: 8.19.3 - ~/.nvm/versions/node/v18.13.0/bin/npm
  Browsers:
    Chrome: 118.0.5993.70
    Firefox: 115.0.2
    Safari: 16.5.2
```

**Comment by shinokada** [comment]
Is it down now?

**Comment by zoltanszogyenyi** [comment]
Hey @shinokada,

This happens if I go to any docs page and then navigate back to the homepage via the logo.

Also happens when I visit when coming from Google - I will attach a video too.

Some other users confirmed this too on Discord.

https://github.com/themesberg/flowbite-svelte/assets/8052108/09e6fa9a-0319-4d08-90a4-74e26a529712

Thank you for looking over this!

Cheers,
Zoltan

**Comment by shinokada** [comment]
It seems it happens when a new commit is pushed and while Vercel is building the deployment.

**Comment by zoltanszogyenyi** [comment]
Hey @shinokada,

Yes, it works now. That could be it.

**Comment by zoltanszogyenyi** [comment]
The website still keeps going down several times a day and I think it's not only when Vercel is building.

For example, now it is down again and I don't think anything happened like a release or deployment.

@shinokada

![image](https://github.com/themesberg/flowbite-svelte/assets/8052108/03dabfff-7e7d-48d9-a81b-3f9743deea3c)

**Comment by shinokada** [comment]
I've done:

- tested locally: `pnpm test:integration`
- build locally and preview: `pnpm build && pnpm preview`

but I can't find any problem.
I will re-deploy on vercel.

**Comment by jackra1n** [comment]
Im also having this issue

macOS 14
Chrome

<img width="865" alt="image" src="https://github.com/themesberg/flowbite-svelte/assets/45038833/031e386c-8dde-4554-ad73-9484199cffd4">

**Comment by zoltanszogyenyi** [comment]
@shinokada our uptime application:

![image](https://github.com/themesberg/flowbite-svelte/assets/8052108/443a07ee-7235-4dca-9832-aff2eee41a96)

**Comment by mvanhalen** [comment]
It seems related to incorrected $page store use. Got it on my local machine.

`
Error: Cannot subscribe to 'page' store on the server outside of a Svelte component, as it is bound to the current request via component context. This prevents state from leaking between users.For more information, see https://kit.svelte.dev/docs/state-management#avoid-shared-state-on-the-server
    at get_store (C:\Users\mvanh\source\repos\flowbite-svelte\node_modules\@sveltejs\kit\src\runtime\app\stores.js:89:9)
    at Object.subscribe (C:\Users\mvanh\source\repos\flowbite-svelte\node_modules\@sveltejs\kit\src\runtime\app\stores.js:35:24)
    at Module.subscribe (C:\Users\mvanh\source\repos\flowbite-svelte\node_modules\svelte\src\runtime\internal\utils.js:139:22)
    at eval (C:/Users/mvanh/source/repos/flowbite-svelte/src/routes/+layout.svelte:36:45)
    at Object.$$render (C:\Users\mvanh\source\repos\flowbite-svelte\node_modules\svelte\src\runtime\internal\ssr.js:156:16)
    at eval (C:/Users/mvanh/source/repos/flowbite-svelte/.svelte-kit/generated/root.svelte:70:129)
    at $$render (C:\Users\mvanh\source\repos\flowbite-svelte\node_modules\svelte\src\runtime\internal\ssr.js:156:16)
    at Object.render (C:\Users\mvanh\source\repos\flowbite-svelte\node_modules\svelte\src\runtime\internal\ssr.js:164:17)
    at Module.render_response (C:/Users/mvanh/source/repos/flowbite-svelte/node_modules/@sveltejs/kit/src/runtime/server/page/render.js:187:29)
    at async Module.render_page (C:/Users/mvanh/source/repos/flowbite-svelte/node_modules/@sveltejs/kit/src/runtime/server/page/index.js:295:10)
`

**Comment by shinokada** [comment]
Can you check [this](https://flowbite-svelte-m8gatwxla-okadashinichi.vercel.app/)? And please let me know if you get the same error.
Thanks.

**Comment by mvanhalen** [comment]
On my mobile got the error.

**Comment by mvanhalen** [comment]
> Can you check https://flowbite-svelte.com it again? And please let me know if you get the same error. Thanks.

Seems to work correctly on desktop now. Maybe mobile was having a cache issue

**Comment by tejesh0** [comment]
Links on search results are also broken: 
Clicking on search suggestion takes to broken link. https://flowbite-svelte.com/docs/components/tab
The correct link is https://flowbite-svelte.com/docs/components/tab

<img width="959" alt="image" src="https://github.com/themesberg/flowbite-svelte/assets/6937958/48c6fb16-32ee-4f40-ab9e-72345b47d3b7">

<img width="703" alt="image" src="https://github.com/themesberg/flowbite-svelte/assets/6937958/6428ae1e-5003-49a6-bcdc-5fe658df2c9d">
