### ISSUE TITLE
Issue with Flowbite-Svelte component in Vercel deployment

### ISSUE THREAD

**Issue by brucey0x** [themesberg/flowbite-svelte#1184]
### Describe the bug

I deployed a recipe tracking app to Github (https://github.com/brucey0x/recipe_tracker) and to Vercel (https://recipe-tracker-budivoogt.vercel.app/), however in the Vercel production build, a weird error related to a Flowbite-Svelte component is showing up that I can't seem to fix.

```
TypeError: n.from is not a function
    at be (AlertModal.24501be2.js:1:2205)
    at HTMLFormElement.c (11.86ec60d8.js:6:10652)
    at HTMLFormElement.<anonymous> (scheduler.24ac21d3.js:1:3787)
```

This error appears after submitting a form to add a recipe. The alert modal is instantiated from my RecipeTable.svelte component:

```
<AlertModal
	showModal={$showDeleteRecipesConfirmation}
	title="You're about to delete all recipes"
	message="Are you sure you want to proceed? This is irreversible."
	confirmButtonText="Yes :bomb:"
	cancelButtonText="No"
	confirmHandler={deleteRecipesHandler}
	cancelHandler={() => ($showDeleteRecipesConfirmation = false)}
	closeHandler={() => ($showDeleteRecipesConfirmation = false)}
/>
```

And here's the modal itself (AlertModal.svelte):

```
<script lang="ts">
	import { Button, Modal } from "flowbite-svelte"

	export let showModal: boolean = false
	export let title = "You're about to delete this recipe"
	export let message = "Are you sure you want to proceed? This is irreversible."
	export let confirmButtonText = "Yes :bomb:"
	export let cancelButtonText = "No"
	export let confirmHandler = () => {}
	export let cancelHandler = () => {}
	export let closeHandler = () => {}
</script>

<Modal bind:open={showModal} on:close={closeHandler} class="w-26" outsideclose>
	<div class="flex flex-col gap-4 text-black">
		<span class=" text-xl font-bold">{title}</span>
		<span>{message}</span>
		<div class="flex flex-row gap-4 mx-auto">
			<Button on:click={confirmHandler} color="red">{confirmButtonText}</Button>
			<Button on:click={cancelHandler} color="green">{cancelButtonText}</Button>
		</div>
	</div>
</Modal>
```

Any idea how to resolve? I'm stuck :/.

### Reproduction

Visit https://recipe-tracker-budivoogt.vercel.app/, create an account and then go to "browse recipes" tab and add a recipe. Upon submission, you'll see the error in console.

### Flowbite version and System Info

```shell
System:
    OS: macOS 14.1.2
    CPU: (10) arm64 Apple M1 Pro
    Memory: 208.53 MB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.17.1 - ~/.nvm/versions/node/v18.17.1/bin/node
    npm: 10.0.0 - ~/.nvm/versions/node/v18.17.1/bin/npm
    pnpm: 8.8.0 - /opt/homebrew/bin/pnpm
  Browsers:
    Chrome: 120.0.6099.71
    Safari: 17.1.2
  npmPackages:
    @sveltejs/kit: ^1.27.7 => 1.27.7 
    flowbite-svelte: ^0.44.20 => 0.44.20 
    svelte: ^4.2.8 => 4.2.8 
    vite: ^4.5.1 => 4.5.1
```

**Comment by brucey0x** [comment]
I tested a local build using pnpm run build and unfortunately the same issue appears. So it may not be a Vercel specific issue, but rather a build issue. If you have any perspectives, please share -- thank you!

**Comment by brucey0x** [comment]
The issue had to do with capitalization of my import statement. Github didn't process the changes despite having made them locally. I committed without the culprit file and then re-added it, which fixed the issue!
