### ISSUE TITLE
Exports is not defined - fresh project with only button

### ISSUE THREAD

**Issue by troncomputers** [themesberg/flowbite-svelte#43]
```
exports is not defined
ReferenceError: exports is not defined
    at /node_modules/flowbite-svelte/dropdowns/dropdownStores.js:2:23
    at instantiateModule (D:\PROJEKTY\tron-shop-web\node_modules\vite\dist\node\chunks\dep-27bc1ab8.js:58525:15)
```
I don't event need to use exported button component in HTML code. It just needs an import
```svelte
<script>
  import { Button } from 'flowbite-svelte';
</script>

<h1>Welcome to SvelteKit</h1>
<p>
  Visit <a href="https://kit.svelte.dev">kit.svelte.dev</a> to read the documentation
</p>
```

If I change `<script>` to `<script lang="ts">` then I'm gettings this error
```
The requested module '/node_modules/flowbite-svelte/dropdowns/dropdownStores.js' does not provide an export named 'dropdownIdStore'
SyntaxError: The requested module '/node_modules/flowbite-svelte/dropdowns/dropdownStores.js' does not provide an export named 'dropdownIdStore'
```
All project setup with flowbite-svelte was based on `Getting Started` from website.

**Comment by troncomputers** [comment]
Does sveltekit's typescript support matter? 

Now I'm getting:
```
Failed to resolve import "./modropdownsdals/dropdownStores" from "node_modules\flowbite-svelte\index.js". Does the file exist?
12:14:19 [vite] Internal server error: Failed to resolve import "./modropdownsdals/dropdownStores" from "node_modules\flowbite-svelte\index.js". Does the file exist?   
  Plugin: vite:import-analysis
  File: D:/PROJEKTY/flowbite-js/node_modules/flowbite-svelte/index.js
  56 |  export { default as Dropdown } from './dropdowns/DropdownDefault.svelte'    
  57 |  export { default as ImgDropdown } from './dropdowns/ImgDropdown.svelte'     
  58 |  export { dropdownIdStore } from'./modropdownsdals/dropdownStores'
     |                                  ^
  59 |
  60 |  // Footers
      at formatError (D:\PROJEKTY\flowbite-js\node_modules\vite\dist\node\chunks\dep-27bc1ab8.js:36435:46)
      at TransformContext.error (D:\PROJEKTY\flowbite-js\node_modules\vite\dist\node\chunks\dep-27bc1ab8.js:36431:19)
      at normalizeUrl (D:\PROJEKTY\flowbite-js\node_modules\vite\dist\node\chunks\dep-27bc1ab8.js:59840:26)
      at async TransformContext.transform (D:\PROJEKTY\flowbite-js\node_modules\vite\dist\node\chunks\dep-27bc1ab8.js:59989:57)
      at async Object.transform (D:\PROJEKTY\flowbite-js\node_modules\vite\dist\node\chunks\dep-27bc1ab8.js:36672:30)
      at async doTransform (D:\PROJEKTY\flowbite-js\node_modules\vite\dist\node\chunks\dep-27bc1ab8.js:55662:29)
```

**Comment by shinokada** [comment]
Sorry for the trouble. Please update it again.

```
npm i -D flowbite-svelte@latest
```

v0.14.6.

Let me know.

**Comment by troncomputers** [comment]
It has something to do with project type checking. Error is the same, but VS Code shows different behavior. 

1. During new project creation, I'm selecting `Add type checking?` -> `None` and I'm able to import like `import { Button } from 'flowbite-svelte';`
2. When I select `Add type checking?` -> `TypeScript` - I'm getting error on import 
```
Could not find a declaration file for module 'flowbite-svelte'. 'D:/PROJEKTY/tron-shop-web/node_modules/flowbite-svelte/index.js' implicitly has an 'any' type.
  If the 'flowbite-svelte' package actually exposes this module, try adding a new declaration (.d.ts) file containing `declare module 'flowbite-svelte';`js(7016)
```
![flowbite_import](https://user-images.githubusercontent.com/29543667/163988503-3652a073-5702-4d43-99f4-8a395dc58d25.png)

After `npm run dev` I am getting the same error with exports

**Project with TS support**
```
PS D:\PROJEKTY\tron-shop-web> npm run dev

> tron-shop-web@0.0.1 dev
> svelte-kit dev


  SvelteKit v1.0.0-next.315

  network: not exposed
  network: not exposed
  local:   http://localhost:3000

  Use --host to expose server to other devices on this network


exports is not defined
ReferenceError: exports is not defined
    at /node_modules/flowbite-svelte/dropdowns/dropdownStores.js:2:23
    at instantiateModule (D:\PROJEKTY\tron-shop-web\node_modules\vite\dist\node\chunks\dep-27bc1ab8.js:58525:15)
```

**Project without TS support**
```
PS D:\PROJEKTY\flowbite-js> npm run dev

> flowbite-js@0.0.1 dev
> svelte-kit dev


  SvelteKit v1.0.0-next.315

  network: not exposed
  network: not exposed
  local:   http://localhost:3000

  Use --host to expose server to other devices on this network


The request url "D:/PROJEKTY/tron-shop-web/.svelte-kit/runtime/client/start.js" is outside of Vite serving allow list.

- D:/PROJEKTY/flowbite-js/src/lib
- D:/PROJEKTY/flowbite-js/src/routes
- D:/PROJEKTY/flowbite-js/.svelte-kit
- D:/PROJEKTY/flowbite-js/src
- D:/PROJEKTY/flowbite-js/node_modules

Refer to docs https://vitejs.dev/config/#server-fs-allow for configurations and more details.

The request url "D:/PROJEKTY/tron-shop-web/.svelte-kit/runtime/client/start.js" is outside of Vite serving allow list.
exports is not defined
ReferenceError: exports is not defined
    at /node_modules/flowbite-svelte/dropdowns/dropdownStores.js:2:23
    at instantiateModule (D:\PROJEKTY\flowbite-js\node_modules\vite\dist\node\chunks\dep-27bc1ab8.js:58525:15)
```

**Comment by shinokada** [comment]
Can you remove package-lock.json and node_modules dir and install it again?

```
rm package-lock.json
rm -rf node_modules
npm i 
```

Please show me your package.json file.

**Comment by shinokada** [comment]
If you still have a problem, can you give me your repo address. I will try it locally.

**Comment by troncomputers** [comment]
Same `exports is not defined` error. [Link to repo](https://github.com/adamwoxwozniak/flowbite-ts-demo)

**Comment by shinokada** [comment]
Thanks. I will check it tomorrow.

**Comment by shinokada** [comment]
Please update it and let me know.

It was my mistakes. I used ts file for svelte/stores and when I create a package, it didn't work well. I updated:

- modal
- dropdown
- tab

by changing file names from ts to js and removed all types from those files.

![image](https://user-images.githubusercontent.com/147320/164106015-74cfbcda-70e3-4021-854f-c793f2a79921.png)

Thank you for reporting the bug. Please let me know if you find more bugs.

**Comment by troncomputers** [comment]
I'm still having an issue here 
```
Error: <Sidebar> is not a valid SSR component. You may need to review your build config to ensure that dependencies are compiled, rather than imported as pre-compiled modules
    at Proxy.validate_component (D:\GITHUB\flowbite-ts-demo\node_modules\svelte\internal\index.js:1722:15)
    at eval (/src/routes/__layout.svelte:65:34)
    at Object.$$render (D:\GITHUB\flowbite-ts-demo\node_modules\svelte\internal\index.js:1745:22)
    at eval (/.svelte-kit/generated/root.svelte:50:126)
    at $$render (D:\GITHUB\flowbite-ts-demo\node_modules\svelte\internal\index.js:1745:22)
    at Object.render (D:\GITHUB\flowbite-ts-demo\node_modules\svelte\internal\index.js:1753:26)
    at render_response (file:///D:/GITHUB/flowbite-ts-demo/.svelte-kit/runtime/server/index.js:1223:27)
    at async respond_with_error (file:///D:/GITHUB/flowbite-ts-demo/.svelte-kit/runtime/server/index.js:2673:10)
    at async respond$1 (file:///D:/GITHUB/flowbite-ts-demo/.svelte-kit/runtime/server/index.js:2927:4)
    at async resolve (file:///D:/GITHUB/flowbite-ts-demo/.svelte-kit/runtime/server/index.js:3302:11)
```

**Comment by shinokada** [comment]
Don't forget to use:

```
import {Sidebar} from 'flowbite-svelte'
```

You didn't have `{}`.

**Comment by jlieth** [comment]
Hello,

I think I'm having a problem related to this (but it's probably because I'm not familiar with configuring Typescript). I use Svelte in a Symfony project with webpack-encore. I installed flowbite and flowbite-svelte. When I try to use any components from flowbite-svelte in my Svelte files, I get these errors:

```
Module build failed: Module not found:
"./node_modules/flowbite-svelte/index.js" contains a reference to the file "./dropdowns/dropdownStores".
This file can not be found, please check it for typos or update it if the file got moved.

"./node_modules/flowbite-svelte/index.js" contains a reference to the file "./modals/modalStores".
This file can not be found, please check it for typos or update it if the file got moved.

"./node_modules/flowbite-svelte/index.js" contains a reference to the file "./tabs/tabStores".
This file can not be found, please check it for typos or update it if the file got moved.
```

I checked and when I change `flowbite-svelte/index.js` to explicitly import from `./dropdowns/dropdownStores.js` (with extension), the error for this file disappears. Like I said, this may just be because my setup isn't properly configured. I tried researching about module resolution order, but I'm feeling a little in over my head with this problem.

`tsconfig.json`:
```json
{
  "extends": "@tsconfig/svelte/tsconfig.json",

  "include": ["./assets/js/**/*"],
  "exclude": ["./node_modules/*", "public/*"],
  "compilerOptions": {
    "module": "esNext",
    "target": "esnext",
    "moduleResolution": "node",
    "paths": {
      "@/*": ["./assets/js/*"],
      "@public/*": ["./public/*"],
    }
  },
  "strict": true,
  "noImplicitAny": false
}
```

`tailwind.config.js`:
```js
module.exports = {
    content: [
        `${__dirname}/assets/js/**/*.svelte`,
        `${__dirname}/node_modules/flowbite-svelte/**/*.{html,js,svelte,ts}`,
    ],
    plugins: [
        require("flowbite/plugin")
    ]
}
```

**Comment by shinokada** [comment]
@jlieth Can you post your package.json file?

**Comment by jlieth** [comment]
`package.json`:
```json
{
    "devDependencies": {
        "@fortawesome/free-solid-svg-icons": "^6.1.1",
        "@symfony/webpack-encore": "^1.7.0",
        "@tsconfig/svelte": "^3.0.0",
        "@types/node": "^17.0.23",
        "@types/tailwindcss": "^3.0.10",
        "autoprefixer": "^10.4.4",
        "core-js": "^3.0.0",
        "flowbite": "^1.4.2",
        "flowbite-svelte": "^0.14.12",
        "fork-ts-checker-webpack-plugin": "^6.5.1",
        "postcss": "^8.4.12",
        "regenerator-runtime": "^0.13.2",
        "svelte": "^3.47.0",
        "svelte-check": "^2.0.0",
        "svelte-fa": "^2.4.0",
        "svelte-loader": "^3.1.2",
        "svelte-preprocess": "^4.10.5",
        "tailwindcss": "^3.0.23",
        "ts-loader": "^9.2.8",
        "tslib": "^2.0.0",
        "typescript": "^4.6.3",
        "webpack-notifier": "^1.6.0"
    },
    "license": "UNLICENSED",
    "private": true,
    "scripts": {
        "dev-server": "encore dev-server",
        "dev": "encore dev",
        "watch": "encore dev --watch",
        "build": "encore production --progress",
        "check": "svelte-check --tsconfig ./tsconfig.json"
    },
    "dependencies": {
        "@inertiajs/inertia": "^0.11.0",
        "@inertiajs/inertia-svelte": "^0.8.0",
        "@inertiajs/progress": "^0.2.7"
    }
}
```
Also did a complete re-install of dependencies (removed `package-lock.json` and `node_modules` dir).

**Comment by jlieth** [comment]
I use npm in a docker container. (Technically my entire setup runs in a docker container).

```console
/var/www/html $ npm cache clean --force
npm WARN using --force Recommended protections disabled.
/var/www/html $ rm package-lock.json
/var/www/html $ rm -rf node_modules
/var/www/html $ npm i
npm WARN deprecated source-map-url@0.4.1: See https://github.com/lydell/source-map-url#deprecated
npm WARN deprecated source-map-resolve@0.5.3: See https://github.com/lydell/source-map-resolve#deprecated
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated

added 763 packages, and audited 764 packages in 56s

79 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
/var/www/html $ npm run dev

> dev
> encore dev

Running webpack ...

 ERROR  Failed to compile with 3 errors                                                                                                    11:18:19 AM

Module build failed: Module not found:
"./node_modules/flowbite-svelte/index.js" contains a reference to the file "./dropdowns/dropdownStores".
This file can not be found, please check it for typos or update it if the file got moved.

"./node_modules/flowbite-svelte/index.js" contains a reference to the file "./modals/modalStores".
This file can not be found, please check it for typos or update it if the file got moved.

"./node_modules/flowbite-svelte/index.js" contains a reference to the file "./tabs/tabStores".
This file can not be found, please check it for typos or update it if the file got moved.

Entrypoint app [big] 9.01 MiB = vendors-node_modules_fortawesome_free-solid-svg-icons_index_es_js-node_modules_inertiajs_iner-0d5e3e.css 13.3 KiB vendors-node_modules_fortawesome_free-solid-svg-icons_index_es_js-node_modules_inertiajs_iner-0d5e3e.js 8.61 MiB app.css 235 KiB app.js 156 KiB
webpack compiled with 3 errors
```

I definitely have the most recent version. It's just that my Typescript setup can't find the Javascript files when imported in the index.js without extension.

**Comment by shinokada** [comment]
I want to test a couple of things. 
Can you update the package and let me know.
Sorry for the trouble and thank you for your help.

```
npm i -D flowbite-svelte@latest
```

It should install v0.14.13.

And let me know the result.

**Comment by jlieth** [comment]
It works fine for me now. :)

Thank you so much for your quick responses and the fix.

**Comment by shinokada** [comment]
I'm glad it is working and happy to help.
Good luck with your project.

**Comment by troncomputers** [comment]
Everything works for me too, so I'm closing ;-)
