### ISSUE TITLE
Svelte Carousel - Cannot read properties of undefined (reading 'length')

### ISSUE THREAD

**Issue by cc222** [themesberg/flowbite-svelte#488]
### Describe the bug

error when using example
`Cannot read properties of undefined (reading 'length')
TypeError: Cannot read properties of undefined (reading 'length')       
    at Carousel.svelte:40:30
    at Object.$$render (/node_modules/svelte/internal/index.mjs:1876:22)
    at eval (/src/routes/+page.svelte:63:125)
    at Object.$$render (/node_modules/svelte/internal/index.mjs:1876:22)
    at Object.default (root.svelte:41:38)
    at eval (/src/routes/+layout.svelte:26:67)
    at Object.$$render (/node_modules/svelte/internal/index.mjs:1876:22)
    at root.svelte:40:37
    at $$render (/node_modules/svelte/internal/index.mjs:1876:22)       
    at Object.render (/node_modules/svelte/internal/index.mjs:1884:26)  `
code:
```
<script>
	import { Carousel } from 'flowbite-svelte';
	export const imageList = [
		{
			id: 0,
			name: 'Cosmic timetraveler',
			imgurl: '/images/carousel/cosmic-timetraveler-pYyOZ8q7AII-unsplash.webp',
			attribution: 'cosmic-timetraveler-pYyOZ8q7AII-unsplash.com'
		},
		{
			id: 1,
			name: 'Cristina Gottardi',
			imgurl: '/images/carousel/cristina-gottardi-CSpjU6hYo_0-unsplash.webp',
			attribution: 'cristina-gottardi-CSpjU6hYo_0-unsplash.com'
		},
		{
			id: 2,
			name: 'Johannes Plenio',
			imgurl: '/images/carousel/johannes-plenio-RwHv7LgeC7s-unsplash.webp',
			attribution: 'johannes-plenio-RwHv7LgeC7s-unsplash.com'
		},
		{
			id: 3,
			name: 'Jonatan Pie',
			imgurl: '/images/carousel/jonatan-pie-3l3RwQdHRHg-unsplash.webp',
			attribution: 'jonatan-pie-3l3RwQdHRHg-unsplash.com'
		},
		{
			id: 4,
			name: 'Mark Harpur',
			imgurl: '/images/carousel/mark-harpur-K2s_YE031CA-unsplash.webp',
			attribution: 'mark-harpur-K2s_YE031CA-unsplash'
		},
		{
			id: 5,
			name: 'Pietro De Grandi',
			imgurl: '/images/carousel/pietro-de-grandi-T7K4aEPoGGk-unsplash.webp',
			attribution: 'pietro-de-grandi-T7K4aEPoGGk-unsplash'
		},
		{
			id: 6,
			name: 'Sergey Pesterev',
			imgurl: '/images/carousel/sergey-pesterev-tMvuB9se2uQ-unsplash.webp',
			attribution: 'sergey-pesterev-tMvuB9se2uQ-unsplash'
		},
		{
			id: 7,
			name: 'Solo travel goals',
			imgurl: '/images/carousel/solotravelgoals-7kLufxYoqWk-unsplash.webp',
			attribution: 'solotravelgoals-7kLufxYoqWk-unsplash'
		}
	];
</script>

<div class="max-w-4xl">
	<Carousel {imageList} />
</div>
```

### Reproduction

code /\
          |

### Flowbite version and System Info

```shell
System:
    OS: Windows 10 10.0.19044
    CPU: (12) x64 Intel(R) Xeon(R) CPU E5-2620 v3 @ 2.40GHz
    Memory: 365.03 MB / 7.84 GB
  Binaries:
    Node: 18.12.1 - C:\Program Files\nodejs\node.EXE
    npm: 8.19.2 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (107.0.1418.42)
    Internet Explorer: 11.0.19041.1566
  npmPackages:
    @sveltejs/kit: ^1.0.0 => 1.0.1
    flowbite-svelte: ^0.28.11 => 0.28.11
    svelte: ^3.54.0 => 3.55.0
    vite: ^4.0.0 => 4.0.1
```

**Comment by shinokada** [comment]
I use `"@sveltejs/kit": "^1.0.1",` etc. but not able to reproduce the errors.

**Comment by chrisShick** [comment]
This looks to be an issue with using only svelte rather than SvelteKit. I am able to reproduce this error when using using svelte installed through vite.

**Comment by chrisShick** [comment]
@cc222 the issue with yours is that you are passing in {imageList} but it should be images="{imageLIst}"
