### ISSUE TITLE
Indicator component is not a valid SSR component

### ISSUE THREAD

**Issue by jackson-jackson** [themesberg/flowbite-svelte#568]
### Describe the bug

After importing and saving the indicator component it get the following error on my local environment:

`Error: <Indicator> is not a valid SSR component. You may need to review your build config to ensure that dependencies are compiled, rather than imported as pre-compiled modules. Otherwise you may need to fix a <Indicator>.
    at Module.validate_component (/node_modules/.pnpm/svelte@3.55.0/node_modules/svelte/internal/index.mjs:1853:15)
    at Object.default (/src/lib/components/navbar/Navbar.svelte:141:30)
    at eval (/node_modules/.pnpm/flowbite-svelte@0.29.10/node_modules/flowbite-svelte/buttons/Button.svelte:163:40)
    at eval (/node_modules/.pnpm/flowbite-svelte@0.29.10/node_modules/flowbite-svelte/buttons/Button.svelte:164:6)
    at Button.svelte:93:8
    at Object.$$render (/node_modules/.pnpm/svelte@3.55.0/node_modules/svelte/internal/index.mjs:1876:22)
    at eval (/src/lib/components/navbar/Navbar.svelte:136:88)
    at Object.$$render (/node_modules/.pnpm/svelte@3.55.0/node_modules/svelte/internal/index.mjs:1876:22)
    at eval (/src/routes/+layout.svelte:41:85)
    at Object.$$render (/node_modules/.pnpm/svelte@3.55.0/node_modules/svelte/internal/index.mjs:1876:22)`

### Reproduction

https://stackblitz.com/edit/sveltejs-kit-template-default-5ggbww?file=src/routes/+page.svelte

### Flowbite version and System Info

```shell
System:
    OS: macOS 13.2
    CPU: (16) x64 Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
    Memory: 32.72 GB / 64.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.14.0 - ~/.nvm/versions/node/v18.14.0/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 9.3.1 - ~/.nvm/versions/node/v18.14.0/bin/npm
  Browsers:
    Chrome: 110.0.5481.77
    Firefox: 108.0.1
    Safari: 16.3
```

**Comment by shinokada** [comment]
Hi,

You need to change the +page.svelte

```
<script>
	import { Navbar } from 'flowbite-svelte'
</script>

<Navbar />
```
